# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sync data regularly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # runs every hour

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Sync data
      env:
        giki_username: ${{ secrets.GIKI_USERNAME }}
        giki_token: ${{ secrets.GIKI_TOKEN }}
      run: node sync.js
    - name: Config git user info
      env: 
        GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      run: |
          git config --global user.email $GIT_USER_EMAIL
          git config --global user.name $GITHUB_ACTOR
    - run: git add .
    - run: git commit -m "Sync data"
    - name: push change
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
      
